service: realworld-api

provider:
  name: aws
  runtime: nodejs8.10
  profile: default
  region: eu-west-2

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    dontPrintOutput: true

functions:
  realworld:
    handler: src/RealWorld/api.handler
    events:
      - http:
          integration: lambda-proxy
          path: /api/
          method: ANY
      - http:
          integration: lambda-proxy
          path: /api/{proxy+}
          method: ANY
